apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bb2fea23j-dotnet-basic
  janus-idp.io/tekton: bb2fea23j-dotnet-basic
  backstage.io/kubernetes-id: bb2fea23j-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bb2fea23j-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
